ABC.exe:main.o big.o fact.o rev.o
        gcc -o ABC.exe main.o big.o fact.o rev.o
main.c:main.o
        gcc -c main.c
big.c:big.o
        gcc -c big.c
fact.c:fact.o
        gcc -c fact.c
rev.c:rev.o
        gcc -c rev.c
